services:
  - type: web
    name: certibuy-project
    runtime: python
    buildCommand: "pip install -r requirements.txt; python manage.py collectstatic --noinput; python manage.py migrate"
    startCommand: "gunicorn certibuy.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "certibuy-project.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: certibuy-db
          property: connectionString

databases:
  - name: certibuy-db
    plan: free
